let mkEffectFn1 _ = undefined
let mkEffectFn2 _ = undefined
let mkEffectFn3 _ = undefined
let mkEffectFn4 _ = undefined
let mkEffectFn5 _ = undefined
let mkEffectFn6 _ = undefined
let mkEffectFn7 _ = undefined
let mkEffectFn8 _ = undefined
let mkEffectFn9 _ = undefined
let mkEffectFn10 _ = undefined
let runEffectFn1 _ _ = undefined
let runEffectFn2 _ _ _ = undefined
let runEffectFn3 _ _ _ _ = undefined
let runEffectFn4 _ _ _ _ _ = undefined
let runEffectFn5 _ _ _ _ _ _ = undefined
let runEffectFn6 _ _ _ _ _ _ _ = undefined
let runEffectFn7 _ _ _ _ _ _ _ _ = undefined
let runEffectFn8 _ _ _ _ _ _ _ _ _ = undefined
let runEffectFn9 _ _ _ _ _ _ _ _ _ _ = undefined
let runEffectFn10 _ _ _ _ _ _ _ _ _ _ _ = undefined
